- name: Build benchmark container
  hosts: "{{ groups['machines'][0] }}"

  tasks:
    - name: Create directories
      shell: |
        mkdir -p /home/{{ ansible_ssh_user }}/libp2p-dog
        mkdir -p /home/{{ ansible_ssh_user }}/libp2p-dog/benchmark

    - name: Copy Cargo.toml to remote machine
      synchronize:
        src: "{{ playbook_dir }}/../../../libp2p-dog/Cargo.toml"
        dest: /home/{{ ansible_ssh_user }}/libp2p-dog/Cargo.toml
        mode: push
        delete: true

    - name: Copy dog directory to remote machine
      synchronize:
        src: "{{ playbook_dir }}/../../../libp2p-dog/dog"
        dest: /home/{{ ansible_ssh_user }}/libp2p-dog/
        mode: push
        delete: true

    - name: Copy benchmark code directory to remote machine
      synchronize:
        src: "{{ playbook_dir }}/../../../libp2p-dog/benchmark/code"
        dest: /home/{{ ansible_ssh_user }}/libp2p-dog/benchmark/
        mode: push
        delete: true

    - name: Copy Dockerfile to remote machine
      synchronize:
        src: "{{ playbook_dir }}/../../../libp2p-dog/benchmark/Dockerfile"
        dest: /home/{{ ansible_ssh_user }}/libp2p-dog/benchmark/Dockerfile
        mode: push
        delete: true

    - name: Copy examples (needed due to workspace dependencies)
      synchronize:
        src: "{{ playbook_dir }}/../../../libp2p-dog/examples"
        dest: /home/{{ ansible_ssh_user }}/libp2p-dog/
        mode: push
        delete: true

    - name: Build container
      shell: |
        docker build \
          -t dog-benchmark:latest \
          -f /home/{{ ansible_ssh_user }}/libp2p-dog/benchmark/Dockerfile \
          /home/{{ ansible_ssh_user }}/libp2p-dog
        docker save dog-benchmark:latest > ~/container.tar

    - name: Copy container to local machine
      synchronize:
        src: container.tar
        dest: /tmp
        mode: pull
        delete: true

- name: Upload benchmark container
  hosts: all

  tasks:
    - name: Copy container to remote machines
      synchronize:
        src: /tmp/container.tar
        dest: /tmp
        mode: push
        delete: true

    - name: Load container
      shell: |
        docker load < /tmp/container.tar
