- name: Establish hosts authenticity
  hosts: all
  gather_facts: false

  tasks:
    - name: Establish hosts authenticity
      become: false
      shell: |
        ssh-keygen -R {{ ansible_host }} 2>/dev/null || true
        ssh-keyscan -t rsa,ecdsa,ed25519 {{ ansible_host }} | grep -v "^#" >> ~/.ssh/known_hosts
      delegate_to: localhost

- name: Initialize all machines
  hosts: all
  become: true

  vars:
    ansible_ssh_user: root

  tasks:
    - name: Update APT packages
      apt:
        autoclean: true
        clean: true
        update_cache: true
        upgrade: full

    - name: Install SNAP package manager
      apt:
        name: snapd
        state: present
    
    - name: Update SNAP packages
      command: snap refresh

    - name: Create user
      user:
        generate_ssh_key: true
        name: bob
        shell: /bin/bash

    - name: Add SSH keys to authorized_keys
      authorized_key:
        user: bob
        key: "{{ item }}"
      with_file:
        - "{{ playbook_dir }}/../config/ssh-public-keys.txt"

    - name: Install Docker
      shell: curl -sSL https://get.docker.com/ | sh

    - name: Add user to Docker group
      user:
        name: bob
        groups: docker
        append: true

    - name: Install NTP and utils
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ntp
        - util-linux-extra
        - sntp

    - name: Upload NTP configuration
      copy:
        src: "{{ playbook_dir }}/../config/ntp.conf"
        dest: /etc/ntpsec/ntp.conf
        owner: root
        group: root
        mode: 0644

    - name: Stop NTP service
      service:
        name: ntp
        state: stopped

    - name: Synchronize manually
      command: sntp ntp1.hetzner.de

    - name: Enable and restart NTP service
      service:
        name: ntp
        enabled: true
        state: restarted

    - name: Update hardware clock
      command: hwclock --systohc
